//      
import {NON_ATOMS} from "./symbols";
                                                   
                                                                       
                                    
                                            
                                   
                                         

                                             
                                                                           

// ParseNode's corresponding to Symbol `Group`s in symbols.js.
                             
                       
                               
                          
                           
                          
                         

// ParseNode from `Parser.formatUnsupportedCmd`
                                                         

// Union of all possible `ParseNode<>` types.
                                                   

// Map from `NodeType` to the corresponding `ParseNode`.
                       
               
                      
                   
                              
                                              
                                      
                         
                           
                             
                                                                  
                                  
                                          
                                                                                
                                            
                        
                       
       
                 
                        
                   
                              
                     
                            
       
                       
                              
                   
                              
                               
       
               
                      
                   
                              
                      
                             
       
                     
                            
                   
                              
                      
       
                                                                                
                                                                      
                                                         
                                              
            
                   
                   
                              
                        
                                     
                                    
                                
                        
                     
                    
           
                   
                   
                              
                        
                                     
                                    
                                
                                                                     
                    
                             
       
                  
                         
                   
                              
                             
                             
       
             
                    
                   
                              
                       
       
              
                     
                   
                              
                           
                         
       
                 
                        
                   
                              
                        
                             
       
                
                       
                   
                              
                            
                            
                            
       
             
                    
                   
                              
                             
                            
       
              
                     
                   
                              
                             
                      
       
             
                    
                   
                              
                    
       
              
                     
                   
                              
                     
                      
       
                                                                         
                                                                            
                          
              
                     
                     
                   
                              
                     
       
                 
                        
                   
                              
                     
       
                 
                        
                   
                              
                     
       
                 
                        
                   
                              
                     
       
                                                                          
                      
                             
                   
                              
                     
       
                  
                         
                   
                              
                     
       
                                                                               
                        
                
                       
                   
                              
                      
                             
                           
                           
       
                     
                            
                   
                              
                      
                             
                           
                           
       
            
                   
                   
                              
                         
                           
       
                     
                            
                   
                              
                            
                                                     
                      
       
                 
                        
                   
                              
                      
                                 
                             
                           
       
                     
                            
                   
                              
                     
                                
       
              
                     
                   
                              
                     
                           
       
                 
                        
                   
                              
                           
                            
                            
                            
                           
                            
                                
                                    
       
              
                     
                   
                              
                             
       
                    
                           
                   
                              
                      
                        
                           
       
              
                     
                   
                              
                     
                             
       
              
                     
                   
                              
                                       
                             
       
                    
                           
                   
                              
                             
                               
       
                         
                                
                   
                              
                    
                           
                            
                                 
                    
       
               
                      
                   
                              
                            
                           
                      
       
                  
                         
                   
                              
       
              
                     
                   
                              
                               
       
             
                    
                   
                              
                          
                           
       
                   
                          
                   
                              
                             
                     
                      
                                                         
       
                         
                                
                   
                              
                      
                                                    
       
                    
                           
                   
                              
                                
                             
                               
                                     
       
                
                       
                   
                              
                      
       
                
                       
                   
                              
                       
                             
                                
       
                      
                             
                   
                              
                             
                                    
                        
                                
       
                  
                         
                   
                              
                           
       
                 
                        
                   
                              
                             
       
                  
                         
                   
                              
                           
       
                  
                         
                   
                              
                           
       
             
                    
                   
                              
                       
                             
       
                  
                         
                   
                              
                        
                           
       
              
                     
                   
                              
                            
                           
                            
       
                
                       
                   
                              
                     
                             
       
               
                      
                   
                              
                           
                             
                            
       
              
                     
                   
                              
                           
                             
       
                   
                          
                   
                              
                           
       
                 
                        
                   
                              
                           
       
                
                       
                   
                              
                      
                           
                             
       
  

/**
 * Asserts that the node is of the given type and returns it with stricter
 * typing. Throws if the node's type does not match.
 */
export function assertNodeType                    (
    node               ,
    type          ,
)                      {
    if (!node || node.type !== type) {
        throw new Error(
            `Expected node of type ${type}, but got ` +
            (node ? `node of type ${node.type}` : String(node)));
    }
    // $FlowFixMe, >=0.125
    return node;
}

/**
 * Returns the node more strictly typed iff it is of the given type. Otherwise,
 * returns null.
 */
export function assertSymbolNodeType(node               )                  {
    const typedNode = checkSymbolNodeType(node);
    if (!typedNode) {
        throw new Error(
            `Expected node of symbol group type, but got ` +
            (node ? `node of type ${node.type}` : String(node)));
    }
    return typedNode;
}

/**
 * Returns the node more strictly typed iff it is of the given type. Otherwise,
 * returns null.
 */
export function checkSymbolNodeType(node               )                   {
    if (node && (node.type === "atom" || NON_ATOMS.hasOwnProperty(node.type))) {
        // $FlowFixMe
        return node;
    }
    return null;
}
